### ISSUE TITLE
소개 페이지를 만드는 건 어떨까요?

### ISSUE THREAD

**Issue by kination** [jungchinet/jungchinet#7]
프로젝트 잘 보고 있습니다~
그런데 github에 Readme 파일이 없어서 처음 프로젝트에 들어오는 사람이 어떤 프로젝트인지 알 수 없는 점이 조금 불편한 것 같습니다. 간단한 소개 문구나 정치넷 주소라도 표시하는 건 어떨까요?

감사합니다.

**Comment by jinwaters** [comment]
의견 감사합니다^^ 반영하겠습니다
